region                   = "us-east-1"
name_prefix              = "itv"
env_name                 = "dev"
source_repo              = "github.com/brasseale/sg-terraform-itv"
site_repo                = "brasseale/sg-demo-site"
site_repo_primary_branch = "master"
developer                = "sam-brasseale"
